### ISSUE TITLE
Need to remove all _core hashes from config files

### ISSUE THREAD

**Issue by thejimbirch** [kanopi/recalendar#4]
https://github.com/kanopi/recalendar/blob/60f5c7343beedc8408141a61eced8612284d6888/config/install/core.entity_form_display.node.rec_event.default.yml#L13

These two lines:
```
_core:
  default_config_hash: 3WOjqML14thJevyEExkpj3wgvI5dscTOA3Y4_A2v7vo
```

**Comment by banoodle** [comment]
Looks good - thanks @phetw !
